services:
  gateway:
    image: reg.chiz.work.gd/gateway:latest
    container_name: gateway
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # Router
      - "traefik.http.routers.gateway.rule=Host(`chiz.work.gd`) && PathPrefix(`/api`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls.certresolver=le"
      # Service internal port
      - "traefik.http.services.gateway-service.loadbalancer.server.port=8002"

      # - "traefik.http.middlewares.gateway-strip.prefixes=/api"
      # - "traefik.http.routers.gateway.middlewares=gateway-strip"

networks:
  proxy:
    external: true
