
networks:
  proxy:
    external: true

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    volumes:
      - /mnt/hdd/nextcloud/nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=nextcloudpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db

      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.${HOST}
      - OVERWRITEHOST=cloud.${HOST}
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://cloud.${HOST}
      - TRUSTED_PROXIES=traefik
      - APACHE_DISABLE_REWRITE_IP=1
    depends_on:
      - nextcloud-db
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.$HOST`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db  
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloudpass
    volumes:
      - /mnt/hdd/nextcloud/nextcloud_db:/var/lib/mysql
    networks:
      - proxy

