FROM jenkins/jenkins:lts

USER root

# ----------------- Системные утилиты и Docker -----------------
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    jq \
    gnupg \
    lsb-release \
    && install -m 0755 -d /etc/apt/keyrings

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
    && chmod a+r /etc/apt/keyrings/docker.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
       > /etc/apt/sources.list.d/docker.list

RUN apt-get update && apt-get install -y \
    docker-ce-cli \
    docker-compose-plugin \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/libexec/docker/cli-plugins \
    && curl -L https://github.com/docker/buildx/releases/download/v0.29.1/buildx-v0.29.1.linux-arm64 \
       -o /usr/libexec/docker/cli-plugins/docker-buildx \
    && chmod +x /usr/libexec/docker/cli-plugins/docker-buildx

USER jenkins
